Импорт NumPy as np

In [2]:
import numpy as np

Создание массива из 10 нулей

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создание массива из 10 единиц

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Массив из 10 пятерок

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Целые число от 10 до 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

четные числа от 10 до 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Создание матрицы 3x3 со значениями в диапазоне от 0 до 8

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Создание единичной матрицы 3x3

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Используйте NumPy для генерации случайного числа от 0 до 1

In [10]:
np.random.rand(1)

array([0.15162514])


Используйте NumPy для создания массива из 25 случайных чисел, отобранных из стандартного нормального распределения

In [11]:
np.random.randn(25)

array([-0.24208281,  0.22414242,  1.67841626, -0.60858594,  0.89120457,
        0.83583312,  1.7900219 , -1.79035671,  0.41564778,  0.44548857,
        0.19304095,  0.37748497,  1.32462755, -0.31736968,  0.18207345,
       -0.74189264, -1.09132432,  1.58253819, -0.10857517, -0.01055749,
       -0.87403909,  2.36056605, -0.17605318, -0.33895496,  0.31652855])


Создайте матрицу 10 на 10 из равномерно удаленных точек от 0.1 до 1( см linspace):

In [12]:
np.linspace(0.1, 1, 100).reshape(10,10)

array([[0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
        0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818],
       [0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
        0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727],
       [0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
        0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636],
       [0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
        0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545],
       [0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
        0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455],
       [0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
        0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364],
       [0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
        0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273],
       [0.73636364, 0.74545455, 0.7545454

Создайте массив из 20 линейно удаленных точек от 0 до 1( см linspace):

In [13]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
mat[2:5, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
mat[3, 4]

np.int64(20)

In [19]:
mat.flatten()[19]

np.int64(20)

In [22]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [26]:
mat[:3, 1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [29]:
mat[4, :]

array([21, 22, 23, 24, 25])

In [28]:
mat[4:5, :]

array([[21, 22, 23, 24, 25]])

In [31]:
mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
mat.sum()

np.int64(325)

In [34]:
mat.std()

np.float64(7.211102550927978)

In [35]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [37]:
mat.sum(axis=1).reshape(5,1)

array([[ 15],
       [ 40],
       [ 65],
       [ 90],
       [115]])